# Automated Setup Script for Windows
# Run this in PowerShell as Administrator

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Binance Futures Bot - Auto Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check admin rights
$currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
$adminRole = [Security.Principal.WindowsBuiltInRole]::Administrator
$isAdmin = $currentUser.Groups -contains (New-Object Security.Principal.WindowsPrincipal($currentUser)).IsInRole($adminRole)

if (-NOT $isAdmin) {
    Write-Host "⚠️  This script needs Administrator privileges." -ForegroundColor Yellow
    Write-Host "Please run PowerShell as Administrator and try again." -ForegroundColor Yellow
    pause
    exit 1
}

# 1. Install Chocolatey (package manager)
Write-Host "→ Checking Chocolatey..." -ForegroundColor Green
if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
    Write-Host "Installing Chocolatey..." -ForegroundColor Yellow
    Set-ExecutionPolicy Bypass -Scope Process -Force
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
} else {
    Write-Host "✓ Chocolatey already installed" -ForegroundColor Green
}

# 2. Install PostgreSQL
Write-Host ""
Write-Host "→ Installing PostgreSQL..." -ForegroundColor Green
choco install postgresql --params "/Password:bot_password_123" -y

# Add PostgreSQL to PATH
$env:Path += ";C:\Program Files\PostgreSQL\15\bin"
[Environment]::SetEnvironmentVariable("Path", $env:Path, "Machine")

# Wait for PostgreSQL to start
Write-Host "Waiting for PostgreSQL to start..." -ForegroundColor Yellow
Start-Sleep -Seconds 10

# 3. Install Node.js
Write-Host ""
Write-Host "→ Installing Node.js..." -ForegroundColor Green
choco install nodejs -y

# 4. Install Git (if not present)
Write-Host ""
Write-Host "→ Installing Git..." -ForegroundColor Green
choco install git -y

# 5. Generate secrets
Write-Host ""
Write-Host "→ Generating secure secrets..." -ForegroundColor Green
python -c "import secrets; print('SECRET_KEY=' + secrets.token_hex(32))" > secrets.txt
python -c "import os; print('ENCRYPTION_KEY=' + os.urandom(32).hex())" >> secrets.txt

$secretLines = Get-Content secrets.txt
$SECRET_KEY = $secretLines[0].Split('=')[1]
$ENCRYPTION_KEY = $secretLines[1].Split('=')[1]

Remove-Item secrets.txt

Write-Host "✓ SECRET_KEY generated (64 hex chars)" -ForegroundColor Green
Write-Host "✓ ENCRYPTION_KEY generated (64 hex chars)" -ForegroundColor Green

# 6. Create database
Write-Host ""
Write-Host "→ Creating database..." -ForegroundColor Green
# Try to create database using psql
try {
    & psql -U postgres -c "CREATE DATABASE binance_bot;" 2>&1 | Out-Null
    Write-Host "✓ Database 'binance_bot' created" -ForegroundColor Green
} catch {
    Write-Host "⚠ Database might already exist or error occurred" -ForegroundColor Yellow
}

# 7. Setup Backend
Write-Host ""
Write-Host "→ Setting up Backend..." -ForegroundColor Green
Set-Location backend

# Create virtualenv
if (-not (Test-Path "venv")) {
    python -m venv venv
}

# Activate virtualenv
.\venv\Scripts\Activate.ps1

# Install dependencies
pip install -r requirements.txt

# Create .env file
Write-Host "Creating .env file..." -ForegroundColor Yellow
$envContent = @"
# Database
DATABASE_URL=postgresql+psycopg2://postgres:bot_password_123@localhost/binance_bot

# Security (Generated by setup script)
SECRET_KEY=$SECRET_KEY
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=10080

# Encryption (Generated by setup script)
ENCRYPTION_KEY=$ENCRYPTION_KEY

# Redis (optional - install Redis if needed)
REDIS_URL=redis://localhost:6379/0

# Binance (ADD YOUR NEW KEYS HERE AFTER SETUP)
BINANCE_API_KEY=YOUR_NEW_BINANCE_API_KEY_HERE
BINANCE_SECRET_KEY=YOUR_NEW_BINANCE_SECRET_HERE

# Application
APP_ENV=production
CORS_ORIGINS=http://localhost:5173,http://localhost:3000
"@

$envContent | Out-File -FilePath ".env" -Encoding UTF8
Write-Host "✓ .env file created" -ForegroundColor Green

# Initialize database tables
Write-Host "Initializing database tables..." -ForegroundColor Yellow
python -c "from app.database import engine, Base; from app import models; Base.metadata.create_all(bind=engine)"
if ($?) {
    Write-Host "✓ Database tables created" -ForegroundColor Green
} else {
    Write-Host "✗ Error creating tables. Check database connection." -ForegroundColor Red
}

# Create admin user
Write-Host ""
Write-Host "Creating admin user..." -ForegroundColor Yellow
$adminResult = python -c "
from app.database import SessionLocal
from app import crud, schemas

db = SessionLocal()
user = crud.create_user(db, schemas.UserCreate(
    email='admin@tradingbot.com',
    password='ChangeMeNow123!',
    full_name='Admin'
))
user.role = 'admin'
user.subscription_status = 'active'
db.commit()
db.close()
print('Admin created')
"
if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Admin user created" -ForegroundColor Green
    Write-Host "  Email: admin@tradingbot.com" -ForegroundColor Cyan
    Write-Host "  Password: ChangeMeNow123!" -ForegroundColor Cyan
    Write-Host "  ⚠️  CHANGE THIS PASSWORD AFTER FIRST LOGIN!" -ForegroundColor Yellow
} else {
    Write-Host "✗ Could not create admin user. Try manually: python setup.py" -ForegroundColor Red
}

Set-Location ..

# 8. Setup Frontend
Write-Host ""
Write-Host "→ Setting up Frontend..." -ForegroundColor Green
Set-Location frontend

if (-not (Test-Path "node_modules")) {
    npm install
}

# Create .env for frontend (if needed for production builds)
$frontendEnv = @"
VITE_API_URL=http://localhost:8000
"@
$frontendEnv | Out-File -FilePath ".env" -Encoding UTF8 -Force

Set-Location ..

# 9. Summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "✓ SETUP COMPLETE!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "NEXT STEPS:" -ForegroundColor Yellow
Write-Host ""
Write-Host "1. IMPORTANT: Add your NEW Binance API keys to backend/.env:" -ForegroundColor Yellow
Write-Host "   BINANCE_API_KEY=your_new_key" -ForegroundColor Gray
Write-Host "   BINANCE_SECRET_KEY=your_new_secret" -ForegroundColor Gray
Write-Host ""
Write-Host "2. Start the backend server:" -ForegroundColor Yellow
Write-Host "   cd backend" -ForegroundColor Gray
Write-Host "   .\venv\Scripts\Activate.ps1" -ForegroundColor Gray
Write-Host "   uvicorn app.main:app --reload --port 8000" -ForegroundColor Gray
Write-Host ""
Write-Host "3. (Optional) Start frontend in another terminal:" -ForegroundColor Yellow
Write-Host "   cd frontend" -ForegroundColor Gray
Write-Host "   npm run dev" -ForegroundColor Gray
Write-Host ""
Write-Host "4. Open browser:" -ForegroundColor Yellow
Write-Host "   API Docs: http://localhost:8000/docs" -ForegroundColor Cyan
Write-Host "   Frontend: http://localhost:5173" -ForegroundColor Cyan
Write-Host ""
Write-Host "Login credentials:" -ForegroundColor White
Write-Host "   Email: admin@tradingbot.com" -ForegroundColor Gray
Write-Host "   Password: ChangeMeNow123!" -ForegroundColor Gray
Write-Host ""
Write-Host "⚠️  CHANGE PASSWORD IMMEDIATELY AFTER LOGIN!" -ForegroundColor Red
Write-Host ""
Write-Host "Press any key to exit..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
